#!/usr/bin/env bun
/**
 * resolve-data.ts — prebuild script for safeframeworks viewer.
 *
 * Reads parquet, csv, and ndjson data files via duckdb. Writes a single
 * TypeScript file (data-resolved.ts) that exports JSON rows keyed by
 * DataSource name. The viewer imports this file — no runtime file reading.
 *
 * Run before dev or build:
 *   bun run samples/resolve-data.ts
 *
 * Regenerate when data files change.
 */

import { execSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";

const DATA_DIR = join(import.meta.dirname, "data");
const OUT_FILE = join(import.meta.dirname, "data-resolved.ts");

const resolved: Record<string, unknown> = {};

for (const file of readdirSync(DATA_DIR)) {
  const ext = extname(file);
  const name = basename(file, ext);
  const filePath = join(DATA_DIR, file);

  if (ext === ".json") {
    // JSON: read directly
    const raw = readFileSync(filePath, "utf-8").trim();
    try {
      resolved[name] = JSON.parse(raw);
    } catch {
      // NDJSON fallback: one JSON object per line
      resolved[name] = raw.split("\n").filter(Boolean).map(l => JSON.parse(l));
    }
  } else if (ext === ".parquet") {
    const out = execSync(`duckdb -json -c "SELECT * FROM read_parquet('${filePath}')"`, {
      encoding: "utf-8", timeout: 10_000,
    }).trim();
    resolved[name] = JSON.parse(out);
  } else if (ext === ".csv") {
    const out = execSync(`duckdb -json -c "SELECT * FROM read_csv('${filePath}', header=true)"`, {
      encoding: "utf-8", timeout: 10_000,
    }).trim();
    resolved[name] = JSON.parse(out);
  }
}

// Write TypeScript export
const lines = [
  `/** Auto-generated by resolve-data.ts — do not edit. Regenerate with: bun run samples/resolve-data.ts */`,
  `export const RESOLVED_DATA: Record<string, unknown> = ${JSON.stringify(resolved)};`,
];

writeFileSync(OUT_FILE, lines.join("\n") + "\n");

const names = Object.keys(resolved);
const totalRows = names.reduce((sum, n) => sum + (Array.isArray(resolved[n]) ? (resolved[n] as any[]).length : 0), 0);
console.log(`resolved ${names.length} data files (${totalRows} total rows) → ${OUT_FILE}`);
